### ISSUE TITLE
Visual Captioner 

### ISSUE THREAD

**Issue by varunnalluru** [CeeZh/LLoVi#2]
Does this code includes visual captioner ?

**Comment by CeeZh** [comment]
We did not release the code for extracting captions. However, we provided the extracted captions in the data link. If you want to try other captioner, you just need to format the captions as ours, then you should be able to directly run this codebase.

**Comment by varunnalluru** [comment]
actually  you have provided the model link for pretrained visual captioner  (LaViLa model ) but can you help me  to load and run this model 
because 
<img width="295" alt="Screenshot 2024-02-02 at 12 13 35 PM" src="https://github.com/CeeZh/LLoVi/assets/147479996/2b38c0ff-b79d-43e3-9d5f-a435ea892abe">
<img width="536" alt="Screenshot 2024-02-02 at 12 14 31 PM" src="https://github.com/CeeZh/LLoVi/assets/147479996/f8308fdb-0bb6-4c5e-82e6-d5660b7801e2">
I am getting like these

**Comment by varunnalluru** [comment]
Dict object is not callable

**Comment by CeeZh** [comment]
You can refer to the LaViLa codebase (https://github.com/facebookresearch/LaViLa) for how to use it. Our checkpoint follows the same structure as the LaViLa base (TSF-B + GPT-2) model. 
For inference, you can refer to the script that LaViLa's authors provided: https://colab.research.google.com/drive/1gHWiEWywIotRivYQTR-8NQ6GJC7sJUe4.

**Comment by varunnalluru** [comment]
what are the values  of the parameters that you have taken to get that accuracy 
for mine everything its giving the response as -1 and the accuracy is 0

**Comment by CeeZh** [comment]
Can you give me more details about your experiments? I setup this repo again and everything works fine on my device.
