### ISSUE TITLE
Scripts for Generating the Caption 

### ISSUE THREAD

**Issue by oximi123** [CeeZh/LLoVi#7]
Hi, is it possible to share the scripts for generating the caption using visual captioner like LLaVA and LaViLa?

**Comment by CeeZh** [comment]
Hi, please see the following code for extracting EgoSchema frames and generating frame captions using LLaVA. You might also need to make it parallel to accelerate.

def extract_es():
    input_base_path = Path('/mnt/opr/ce/datasets/EgoSchema/videos')
    output_base_path = Path('/mnt/opr/ce/datasets/EgoSchema/images')
    fps = 1
    pbar = tqdm(total=len(list(input_base_path.iterdir())))
    for video_fp in input_base_path.iterdir():
        output_path = output_base_path / video_fp.stem
        output_path.mkdir(parents=True, exist_ok=True)
        vidcap = cv2.VideoCapture(str(video_fp))
        count = 0
        success = True
        fps_ori = int(vidcap.get(cv2.CAP_PROP_FPS))   
        frame_interval = int(1 / fps * fps_ori)
        while success:
            success, image = vidcap.read()
            if not success:
                break
            if count % (frame_interval) == 0 :
                cv2.imwrite(f'{output_path}/{count}.jpg', image)
            count+=1
        pbar.update(1)
    pbar.close()

def llava_es_sub_sequential():
    # hparams and model init
    max_token = 100
    num_words = 10
    model_id = "llava-hf/llava-1.5-7b-hf"
    pipe = pipeline("image-to-text", model=model_id, device=1)
    prompt = f"Describe the image in {num_words} words."
    prompt = f"USER: <image>\n{prompt}\nASSISTANT:"

    # get subset uids
    es_subset_keys = set(load_json('/mnt/opr/ce/datasets/EgoSchema/subset_answers.json').keys())

    resume = True
    output_base_path = Path(f'/mnt/opr/ce/datasets/EgoSchema/captions/llava/subset/words_{num_words}')
    output_base_path.mkdir(parents=True, exist_ok=True)
    base_path = Path('/mnt/opr/ce/datasets/EgoSchema/images')
    example_path_list = [el for el in base_path.iterdir() if el.stem in es_subset_keys]

    pbar = tqdm(total=len(example_path_list))
    for example_path in example_path_list:
        example_output_path = output_base_path / f'{example_path.name}.json'
        if resume and example_output_path.exists():
            pbar.update(1)
            continue
        narr_list = []
        image_paths = list(example_path.iterdir())
        image_paths.sort(key=lambda x: int(x.stem))
        for image_path in image_paths:
            image = Image.open(str(image_path))
            outputs = pipe(image, prompt=prompt, generate_kwargs={"max_new_tokens": max_token})
            outputs = str(outputs[0]['generated_text'])
            idx = outputs.find("ASSISTANT")
            generated_text = outputs[idx+11:]
            narr_list.append(generated_text)
        pbar.update(1)
        save_json(narr_list, example_output_path)
    pbar.close()

**Comment by CeeZh** [comment]
Hi, please see the following code for extracting EgoSchema frames and generating frame captions using LLaVA. You might also need to make it parallel to accelerate.

```python
def extract_es():
    input_base_path = Path('/mnt/opr/ce/datasets/EgoSchema/videos')
    output_base_path = Path('/mnt/opr/ce/datasets/EgoSchema/images')
    fps = 1
    pbar = tqdm(total=len(list(input_base_path.iterdir())))
    for video_fp in input_base_path.iterdir():
        output_path = output_base_path / video_fp.stem
        output_path.mkdir(parents=True, exist_ok=True)
        vidcap = cv2.VideoCapture(str(video_fp))
        count = 0
        success = True
        fps_ori = int(vidcap.get(cv2.CAP_PROP_FPS))   
        frame_interval = int(1 / fps * fps_ori)
        while success:
            success, image = vidcap.read()
            if not success:
                break
            if count % (frame_interval) == 0 :
                cv2.imwrite(f'{output_path}/{count}.jpg', image)
            count+=1
        pbar.update(1)
    pbar.close()

def llava_es_sub_sequential():
    # hparams and model init
    max_token = 100
    num_words = 10
    model_id = "llava-hf/llava-1.5-7b-hf"
    pipe = pipeline("image-to-text", model=model_id, device=1)
    prompt = f"Describe the image in {num_words} words."
    prompt = f"USER: <image>\n{prompt}\nASSISTANT:"

    # get subset uids
    es_subset_keys = set(load_json('/mnt/opr/ce/datasets/EgoSchema/subset_answers.json').keys())

    resume = True
    output_base_path = Path(f'/mnt/opr/ce/datasets/EgoSchema/captions/llava/subset/words_{num_words}')
    output_base_path.mkdir(parents=True, exist_ok=True)
    base_path = Path('/mnt/opr/ce/datasets/EgoSchema/images')
    example_path_list = [el for el in base_path.iterdir() if el.stem in es_subset_keys]

    pbar = tqdm(total=len(example_path_list))
    for example_path in example_path_list:
        example_output_path = output_base_path / f'{example_path.name}.json'
        if resume and example_output_path.exists():
            pbar.update(1)
            continue
        narr_list = []
        image_paths = list(example_path.iterdir())
        image_paths.sort(key=lambda x: int(x.stem))
        for image_path in image_paths:
            image = Image.open(str(image_path))
            outputs = pipe(image, prompt=prompt, generate_kwargs={"max_new_tokens": max_token})
            outputs = str(outputs[0]['generated_text'])
            idx = outputs.find("ASSISTANT")
            generated_text = outputs[idx+11:]
            narr_list.append(generated_text)
        pbar.update(1)
        save_json(narr_list, example_output_path)
    pbar.close()
```

**Comment by oximi123** [comment]
> Hi, please see the following code for extracting EgoSchema frames and generating frame captions using LLaVA. You might also need to make it parallel to accelerate.
> 
> ```python
> def extract_es():
>     input_base_path = Path('/mnt/opr/ce/datasets/EgoSchema/videos')
>     output_base_path = Path('/mnt/opr/ce/datasets/EgoSchema/images')
>     fps = 1
>     pbar = tqdm(total=len(list(input_base_path.iterdir())))
>     for video_fp in input_base_path.iterdir():
>         output_path = output_base_path / video_fp.stem
>         output_path.mkdir(parents=True, exist_ok=True)
>         vidcap = cv2.VideoCapture(str(video_fp))
>         count = 0
>         success = True
>         fps_ori = int(vidcap.get(cv2.CAP_PROP_FPS))   
>         frame_interval = int(1 / fps * fps_ori)
>         while success:
>             success, image = vidcap.read()
>             if not success:
>                 break
>             if count % (frame_interval) == 0 :
>                 cv2.imwrite(f'{output_path}/{count}.jpg', image)
>             count+=1
>         pbar.update(1)
>     pbar.close()
> 
> def llava_es_sub_sequential():
>     # hparams and model init
>     max_token = 100
>     num_words = 10
>     model_id = "llava-hf/llava-1.5-7b-hf"
>     pipe = pipeline("image-to-text", model=model_id, device=1)
>     prompt = f"Describe the image in {num_words} words."
>     prompt = f"USER: <image>\n{prompt}\nASSISTANT:"
> 
>     # get subset uids
>     es_subset_keys = set(load_json('/mnt/opr/ce/datasets/EgoSchema/subset_answers.json').keys())
> 
>     resume = True
>     output_base_path = Path(f'/mnt/opr/ce/datasets/EgoSchema/captions/llava/subset/words_{num_words}')
>     output_base_path.mkdir(parents=True, exist_ok=True)
>     base_path = Path('/mnt/opr/ce/datasets/EgoSchema/images')
>     example_path_list = [el for el in base_path.iterdir() if el.stem in es_subset_keys]
> 
>     pbar = tqdm(total=len(example_path_list))
>     for example_path in example_path_list:
>         example_output_path = output_base_path / f'{example_path.name}.json'
>         if resume and example_output_path.exists():
>             pbar.update(1)
>             continue
>         narr_list = []
>         image_paths = list(example_path.iterdir())
>         image_paths.sort(key=lambda x: int(x.stem))
>         for image_path in image_paths:
>             image = Image.open(str(image_path))
>             outputs = pipe(image, prompt=prompt, generate_kwargs={"max_new_tokens": max_token})
>             outputs = str(outputs[0]['generated_text'])
>             idx = outputs.find("ASSISTANT")
>             generated_text = outputs[idx+11:]
>             narr_list.append(generated_text)
>         pbar.update(1)
>         save_json(narr_list, example_output_path)
>     pbar.close()
> ```

Thanks for your timely response! I have a small question about this code. According to your paper, the caption is generated by several images (determined by the sampling rate) for each video clip. However, in this piece of code, you simply sample frames from the video and generate a caption for each sampled frame, which is not clip-level as mentioned in the paper. How can I transform it to generate clip-level caption?

**Comment by CeeZh** [comment]
Hi,

Sorry for the confusion. The above code shows how to extract captions using LLaVA (an image-level captioner). For clip-level captioner, we used LaViLa (https://github.com/facebookresearch/LaViLa). You can refer to the inference code of LaViLa to see how to extract clip-level captions. Also, the clip sampling rate in Table 4 actually means how to sample short clips from the long video. When a clip is sampled from the video, we simply feed it to LaViLa following the default settings.
